services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: jejak_gpl
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - jejak_mysql:/var/lib/mysql

volumes:
  jejak_mysql:
